# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-16 12:03
from __future__ import unicode_literals

from django.db import migrations, models
import django_countries.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RunnedTest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(blank=True, max_length=30)),
                ('datetime', models.DateTimeField(auto_now_add=True)),
                ('input_file', models.FileField(blank=True, upload_to='uploads/', verbose_name='Blood markers file')),
                ('predicted_age', models.FloatField(blank=True, default='0', verbose_name='Predicted age')),
                ('age', models.FloatField(blank=True, default=0, verbose_name='Age')),
                ('sex', models.IntegerField(blank=True, choices=[(0, 'Female'), (1, 'Male')], default=1, verbose_name='Sex')),
                ('weight', models.FloatField(blank=True, default='0', verbose_name='Weight')),
                ('height', models.FloatField(blank=True, default='0', verbose_name='Height')),
                ('bmi', models.FloatField(blank=True, default='0', verbose_name='BMI')),
                ('smoking', models.IntegerField(blank=True, choices=[(0, 'Never smoked'), (1, 'Former smoker'), (2, 'Current light smoker'), (3, 'Current heavy smoker')], default=0, verbose_name='Smoking')),
                ('alcohol', models.IntegerField(blank=True, choices=[(0, 'non-drinker'), (1, '< 1 drink/month'), (2, '0-4/week'), (3, '5-9/week'), (4, '10-24/week'), (5, 'binger')], default=0, verbose_name='Alcohol')),
                ('ethnicity', django_countries.fields.CountryField(max_length=2)),
                ('social_status', models.IntegerField(blank=True, choices=[(0, 'Poor'), (1, 'Good')], default=1, verbose_name='Social status')),
                ('activity', models.IntegerField(blank=True, choices=[(0, 'Low'), (1, 'Moderate'), (2, 'High')], default=0, verbose_name='Activity')),
                ('mental_health', models.IntegerField(blank=True, choices=[(0, 'No active illness'), (1, 'Active illness')], default=0, verbose_name='Mental health')),
            ],
        ),
    ]
