# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-16 18:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='runnedtest',
            name='expected_longevity',
            field=models.FloatField(blank=True, default=0, verbose_name='Expected Longevity'),
        ),
    ]
