# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-17 13:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_runnedtest_expected_longevity'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idx', models.CharField(help_text="Used to place text in the required container on page. Don't change", max_length=300, verbose_name='Identificator')),
                ('header', models.CharField(help_text='Text header', max_length=300, verbose_name='Identificator')),
                ('text', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='runnedtest',
            name='alcohol',
            field=models.IntegerField(blank=True, choices=[(0, 'Non-drinker'), (1, '< 1 drink/month'), (2, '0-4/week'), (3, '5-9/week'), (4, '10-24/week'), (5, 'Heavy drinker')], default=0, verbose_name='Alcohol'),
        ),
        migrations.AlterField(
            model_name='runnedtest',
            name='input_file',
            field=models.FileField(blank=True, upload_to=b'', verbose_name='Blood markers file'),
        ),
    ]
