# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-23 12:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_auto_20160817_1352'),
    ]

    operations = [
        migrations.AddField(
            model_name='runnedtest',
            name='metric',
            field=models.CharField(blank=True, default='eu', max_length=2),
        ),
        migrations.AlterField(
            model_name='article',
            name='header',
            field=models.CharField(help_text='Text header', max_length=300, verbose_name='Header'),
        ),
    ]
